export enum PaymentMod {
  MP_01 = 'Contanti',
  MP_02 = 'Assegno',
  MP_03 = 'Assegno circolare',
  MP_04 = 'Contanti presso Tesoreria',
  MP_05 = 'Bonifico',
  MP_06 = 'Vaglia cambiario',
  MP_07 = 'Bollettino bancario',
  MP_08 = 'Carta di pagamento',
  MP_09 = 'RID',
  MP_10 = 'RID utenze',
  MP_11 = 'RID veloce',
  MP_12 = 'RIBA',
  MP_13 = 'MAV',
  MP_14 = 'Quietanza erario',
  MP_15 = 'Giroconto su conti di contabilità speciale',
  MP_16 = 'Domiciliazione bancaria',
  MP_17 = 'Domiciliazione postale',
  MP_18 = 'Bollettino di c/c postale',
  MP_19 = 'SEPA Direct Debit',
  MP_20 = 'SEPA Direct Debit CORE',
  MP_21 = 'SEPA Direct Debit B2B',
  MP_22 = 'Trattenuta su somme già riscosse'
}
